# Generated by Django 5.0.4 on 2024-05-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='delete_after',
            field=models.CharField(choices=[('5', '5 minutes'), ('10', '10 minutes'), ('30', '30 minutes'), ('60', '1 hour'), ('1440', '24 hours')], default='5', max_length=4),
        ),
    ]
