# Generated by Django 5.0.4 on 2024-05-01 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_block_delete_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='updated',
        ),
    ]
